server:
  port: 8001
  servlet:
    contextPath: /${spring.application.name}

spring:
  application:
    name: project-eureka-server
  security:
    user:
      name: user
      password: e958c987-568c-4836-8b7b-58b46914d070
  cloud.config.enabled: false

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.web: WARN
    org.springframework.web.HttpLogging: WARN
    org.springframework.security: WARN
    org.springframework.security.oauth2: WARN
    org.springframework.core.codec.StringDecoder: WARN
    reactor.netty.resources: WARN
    sun.net.www.protocol.http: WARN
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix: DEBUG

eureka:
  instance:
    hostname: ${spring.application.name}
  server:
    hostname: localhost
    port: 8001
  client:
    enabled: true
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://user:e958c987-568c-4836-8b7b-58b46914d070@${eureka.server.hostname}:${eureka.server.port}/${spring.application.name}/eureka

management:
  endpoints.web.exposure.include: info, health, metrics