server:
  port: 8001
  servlet:
    contextPath: /${spring.application.name}

spring:
  application:
    name: project-eureka-server
  security:
    user:
      name: user
      password: e958c987-568c-4836-8b7b-58b46914d070

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
