version: '2.1'

services:
  wiremock:
    build: ./docker-images/wiremock/
    image: project-integration-tests/wiremock:latest
    environment:
      - WIREMOCK_VERSION=2.24.1
    ports:
      - 9090:9090
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 9090" ]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - service-component-tests
    logging:
      driver: none

networks:
  service-component-tests:
    driver: bridge